default_platform(:ios)

platform :ios do
  desc "Windowsからの命令を受け取り、自動でTestFlightへ出荷する"
  lane :deploy_to_testflight do
    
    build_app(
      project: "./Builds/iOS/Unity-iPhone.xcodeproj",
      scheme: "Unity-iPhone",
      export_method: "app-store",
      output_directory: "./build",
      output_name: "8bit-Telephone.ipa",
      clean: true,
      xcargs: "DEVELOPMENT_TEAM='M433M58324' CODE_SIGN_STYLE='Automatic' -allowProvisioningUpdates" 
    )

    # ▼ APIキーを使ってログインする魔法の呪文 ▼
    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_API_KEY_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_API_KEY_KEY"],
      is_key_content_base64: false
    )

    upload_to_testflight(
      skip_waiting_for_build_processing: true,
      api_key: api_key # ⬅️ 先ほど作った username: は消して、これを追加します
    )
  end
end