default_platform(:ios)

platform :ios do
  desc "Windowsからの命令を受け取り、自動でTestFlightへ出荷する"
  lane :deploy_to_testflight do
    
    # 2. Xcodeを開かずに裏側で自動ビルド（アーカイブ）して.ipaファイルを作る
    build_app(
      project: "Unity-iPhone.xcodeproj",
      scheme: "Unity-iPhone",
      export_method: "app-store",
      output_directory: "./build",
      output_name: "8bit-Telephone.ipa",
      clean: true,
      # ▼ ここを修正！Team IDを指定して、Xcodeに自動で証明書を生成させます ▼
      xcargs: "DEVELOPMENT_TEAM='M433M58324' -allowProvisioningUpdates" 
    )

    # 3. 出来上がったアプリをAppleのTestFlightへ自動アップロードする
    upload_to_testflight(
      skip_waiting_for_build_processing: true
    )
  end
end