default_platform(:ios)

platform :ios do
  desc "Windowsからの命令を受け取り、自動でTestFlightへ出荷する"
  lane :deploy_to_testflight do
    
    # ※工程1（update_project_provisioning）は削除しました！

    # 2. Xcodeを開かずに裏側で自動ビルド（アーカイブ）して.ipaファイルを作る
    build_app(
      project: "Unity-iPhone.xcodeproj",
      scheme: "Unity-iPhone",
      export_method: "app-store",
      output_directory: "./build",
      output_name: "8bit-Telephone.ipa",
      clean: true,
      export_xcargs: "-allowProvisioningUpdates" # ⬅️ ココに1行追加！（Xcodeに証明書更新を許可する魔法の呪文）
    )

    # 3. 出来上がったアプリをAppleのTestFlightへ自動アップロードする
    upload_to_testflight(
      skip_waiting_for_build_processing: true
    )
  end
end