name: Deploy iOS App to TestFlight

# どんな時に自動化を起動するか？
on:
  workflow_dispatch:
  push:
    # masterブランチに、Builds/iOSフォルダの中身がPushされた時だけ動かす
    branches:
      - master
    paths:
      - 'Builds/iOS/**'

# 実行する内容
jobs:
  build_and_deploy:
    # どこで動かすか？ ➔ さっきMacに設定した「self-hosted」のロボットを使う！
    runs-on: self-hosted

    steps:
      # 1. GitHubから最新のコードをMacにダウンロードする
      - name: Checkout Code
        uses: actions/checkout@v3
        with:        # ⬅️ ココを追加！
          lfs: true

      # 2. Fastlaneを使ってTestFlightへ自動出荷する
      - name: Run Fastlane Deploy
        # MacのiOSフォルダに移動して、先ほど作った deploy_to_testflight の命令を実行する
        run: fastlane deploy_to_testflight
        env:
          # ▼ App専用パスワードは消して、以下の3つを追加します ▼
          APP_STORE_CONNECT_API_KEY_ISSUER_ID: "efceaad5-96a7-4a33-81f6-b53487d16805"
          APP_STORE_CONNECT_API_KEY_KEY_ID: "7LFPFQ5W64"
          # ※改行を含めてそのまま貼り付けるため、`|` を使います
          APP_STORE_CONNECT_API_KEY_KEY: |
            -----BEGIN PRIVATE KEY-----
            MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgZ9NGbkO36R072Quv
            l7GNmoVcT4YuLryf4gUdU19MZqKgCgYIKoZIzj0DAQehRANCAASzgdM/ckvuoy5s
            zkSXyEpHjZMvfVLqo+8fqHYK2h10Azj5XcejpPa/50DZlE7jpTi3KtxUL8GhhtKs
            O+rXHjg+
            -----END PRIVATE KEY-----